config/routes.rb
Foodwithus::Application.routes.draw do
  resources :groups

  get '/login', :to => 'sessions#new', :as => 'login'
  get '/logout', :to => 'sessions#destroy', :as => 'logout'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  get '/about', to: 'pages#about'
  get '/privacy', to: 'pages#privacy'

  root :to => 'groups#index'
end

app/models/group.rb
class Group < ActiveRecord::Base

  attr_accessible :name
  
  belongs_to :user

  has_many :groups_friends, :dependent => :destroy
  has_many :friends, :through => :groups_friends

  validates :name, :presence => true
  validates_associated :user

  def members
    group_members = []
    group_members.tap { group_members.concat( friends ).push( self.user ) }
  end

  def set_members(friend_id_collection)
    if friend_id_collection == nil
      self.friends = []
    else
      valid_ids = clean_strings_for_ids(friend_id_collection).select do |check_id|
        self.user.friends.include?( Friend.find(check_id.to_i) )
      end
      self.friends = valid_ids.map { |id| Friend.find(id) }
    end
  end

  def top_categories
    profile_counter = {}
    members.each do |member|
      member.instance_of?(User) ? profiles = member.user_profiles : profiles = member.friend_profiles

      unless profiles.empty?
        profiles.each do |profile|
          unless profile.count.nil?
            if profile_counter.has_key?(profile.category_id)
              profile_counter[profile.category_id] += 1
            else
              profile_counter[profile.category_id] = 1
            end
          end
        end
      end
    end

    top_three(profile_counter)
  end

  def nearby_food_choices(group, gps_lat, gps_lon)
    client       = FoursquareWrapper.new(group.user)
    category_ids = top_categories.map { |category| category.fsq_id }
    gps_coord    = clean_gps_for_search( gps_lat, gps_lon )

    if gps_coord

      unless top_categories.empty?
        client.search_nearby_categories(gps_coord, category_ids)
      else
        convert_format_to_category_display( client.search_nearby_food(gps_coord) )
      end

    else
      return false
    end
  end

  private

    def top_three(profile_hash)
      top_three_profiles = exclude_unwanted_categories(profile_hash).sort_by {|k,v| -v}[0...3]

      top_three_profiles.map do |key, value|
        Category.find(key)
      end
    end

    def exclude_unwanted_categories(hash_to_clean)
      hash_to_clean.reject { |k,v| Category.find(k).name == 'Coffee Shop' }
    end

    def clean_gps_for_search(lat, lon)
      gps_lat = remove_spaces(lat)
      gps_lon = remove_spaces(lon)

      if valid_float?(gps_lat) && valid_float?(gps_lon)
        "#{gps_lat},#{gps_lon}"
      else
        return false
      end
    end

    def convert_format_to_category_display(foursquare_response)
      foursquare_response.map do |result|
        begin
          new_mashie            = Hashie::Mash.new
          new_mashie[:name]     = result.venue.name
          new_mashie[:contact]  = { :formattedPhone => result.venue.contact.formattedPhone }
          new_mashie[:location] = { :address => result.venue.location.address,
                                    :city => result.venue.location.city,
                                    :state => result.venue.location.state,
                                    :cc => result.venue.location.cc,
                                    :postalCode => result.venue.location.postalCode 
                                  }
          new_mashie
        rescue Exception => e
          logger.debug e
        end
      end
    end

    def remove_spaces(string)
      string.gsub(/\s+/, "")
    end

    def valid_float?(value)
      !!Float(value) rescue false
    end

    def clean_strings_for_ids(collection)
      collection.select! { |input_id| input_id.to_i != 0 }
      collection.map { |string_id| string_id.to_i }
    end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    current_user ? @groups = current_user.groups : false

    respond_to :html
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    unless params[:lat].nil? || params[:lon].nil?
      @foursquare_results = @group.nearby_food_choices(@group, params[:lat], params[:lon])
    else
      @foursquare_results = nil
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = current_user.groups.build

    respond_to :html
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups.build(:name => params[:group][:name])
    @group.set_members(params[:member])

    if @group.save
      redirect_to root_path
    else
      render 'new'
    end

  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])
    @group.name = params[:group][:name]
    @group.set_members(params[:member])

    if @group.save
      redirect_to root_path
    else
      render 'edit'
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to groups_path
  end
end

app/helpers/groups_helper.rb
module GroupsHelper

  def prepopulated_group_name
    description = %w(Scrumptious Food Edible Spicy Tasty Flavorful Delicious Great Hungry).sample
    grouping = %w(Eats Party Band Troop Feast Nuggets Outing Train Time Bites).sample
    "#{description} #{grouping}"
  end

  def display_top_categories(group)
    group.top_categories.map {|category| category.short_name }.to_sentence
  end

end

app/views/groups/_display_group.html.erb
<% @groups.each do |group| %>
      
  <li>
    <%= link_to group.name, edit_group_path(group), class: 'group_name' %>

    <% unless group.members.empty? %>
      <div class="search_nearby">
        <%= link_to 'Find food', group_path(group), class: 'explore_nearby btn primary' %>
      </div>
      <div class="clearfix"></div>
      <% group.members.each do |member| %>
        <%= link_to ( edit_group_path(group) ) do %>
          <img src='<%= member.photo %>' width='40' height='40' title='<%= member.first_name %> <%= member.last_name %>' />
        <% end %>
      <% end %>
      <br/>
      <span class="group_cuisines"><%= display_top_categories(group) %></span>
    <% end %>
  </li>

<% end %>

app/views/groups/_form.html.erb
<div class="group_form">
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field new_group_name">
    <%= f.label :name %>
    <% if params[:action] == 'new' %>
      <%= f.text_field :name, :value => prepopulated_group_name, size: 40 %>
    <% else %>
      <%= f.text_field :name %>
    <% end %>
  </div>

  <% current_user.friends.each do |friend| %>
    <% @group.friends.include?(friend) ? member_status=true : member_status=false %>
    <div class="group_member">

      <input type="checkbox" name="member[]" value="<%= friend.id %>" id="<%= friend.id %>" 
      <% unless @group.friends.empty? %><% if member_status %>checked<% end %><% end %> 
      />
        
      <label for="<%= friend.id %>">

        <img src='<%= friend.photo %>' width='28' height='28' title='<%= friend.first_name %> <%= friend.last_name %>' />
        
        <div class="member_name"><%= friend.first_name %> <%= friend.last_name %></div>
        <div class="clearfix"></div>

        <% unless friend.categories.empty? %>
          <div class="member_categories">
            Enjoys: 
            <% friend.categories.map do |category| %>
              <%= category.short_name %>
            <% end %>
          </div>
        <% end %>

      </label>
      <div class="clearfix"></div>

    </div>
  <% end %>

  <%= f.submit :class => "btn new" %>

<% end %>
</div>

app/views/groups/edit.html.erb
<div id="group_wrap">
<h1>Group members</h1>
<div class="clearfix"></div>

<%= render 'form' %>

<%= link_to 'Delete this group', @group, class: 'btn danger', method: :delete, data: { confirm: 'Delete this group?' } %>

</div>

app/views/groups/index.html.erb
<div id="group_wrap">
<% if @groups %>

  <h1>Groups</h1>
  <%= link_to 'Create new group of friends', new_group_path, id: "new_group", class: "btn new" %>
  <div class="clearfix"></div>

  <ul id="display_groups">
  <% if @groups.empty? %>
    <p class="empty notice">
      <%= link_to 'Create groups of friends', new_group_path %> & find restaurants nearby based on each group's tastes.
      <br/>
      <br/>
      <%= link_to 'Lets create a group of friends!', new_group_path %>
    </p>
  <% else %>
    <%= render 'groups/display_group' %>
  <% end %>
  </ul>

<% end %>

</div>

app/views/groups/new.html.erb
<div id="group_wrap">
<h1>Create a group of friends</h1>
<div class="clearfix"></div>

<%= render 'form' %>

<%= link_to 'Back to all groups', groups_path, class: 'btn return' %>

</div>

app/views/groups/show.html.erb
<h1>Suggestions for <%= @group.name %></h1>
<div class="clearfix"></div>

<% unless @foursquare_results.nil? %>
  <% @foursquare_results.each do |venue| %>
    <div class="show_nearby_venue">
      <h3><%= venue.name %></h3>
      <%= venue.contact.formattedPhone %>
      <p>
      <%= venue.location.address %><br/>
      <%= venue.location.city %>, <%= venue.location.state %> <%= venue.location.cc %> <%= venue.location.postalCode %>
      </p>
    </div>
  <% end %>

<% else %>

  <p class="empty notice">Please enable GPS to find nearby restaurants.</p>

<% end %>

<%= link_to 'Back to all groups', groups_path, class: 'btn return' %>