config/routes.rb
Foodwithus::Application.routes.draw do
  resources :groups

  get '/login', :to => 'sessions#new', :as => 'login'
  get '/logout', :to => 'sessions#destroy', :as => 'logout'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  get '/about', to: 'pages#about'
  get '/privacy', to: 'pages#privacy'

  root :to => 'groups#index'
end

app/views/layouts/_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34781094-5']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/_dev_info.html.erb
<% if Rails.env.development? %>
  <div id="dev-tools" style="border:10px solid #eee;margin-top:30px;text-align:center;">
    <strong>DEV</strong> <%= params %>
  </div>
<% end %>

app/views/layouts/_welcome.html.erb
<body class="welcome-page">

  <div id="welcome">
    <header><%= link_to 'Food With Us', root_path %></header>

    <p id="tagline">We help you decide where to eat nearby with friends.</p>
    <p id="login"><%= link_to "Login with Foursquare", login_path %> to get started.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food With Us</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<% if public_page? %>
<body class="groups-wrap">
  <div id="page-wrap">
    <%= yield %>

<% elsif current_user %>
  <body class="groups-wrap">

  <div id="page-wrap">

    <header class="clearfix">
      <%= link_to 'Food With Us', root_path, class: "logo" %> 
      <nav><span id="user_name"><%= current_user.first_name %></span> <%= link_to "Logout", logout_path %></nav>
    </header>

    <div id="content-wrap">
      <%= yield %>
    </div>

<% else %>

  <%= render 'layouts/welcome' %>  

<% end %>
  <footer>
    2013 &middot; by <%= link_to '@rexfeng', 'http://twitter.com/rexfeng' %> 
    &middot; <%= link_to 'Github source', 'http://github.com/xta/foodwithus' %>
    &middot; <%= link_to 'About', about_path %>
    &middot; <%= link_to 'Privacy', privacy_path %>
  </footer>
</div>

<%# render 'layouts/dev_info' %>
<%= render 'layouts/analytics' %>
</body>
</html>